### ISSUE TITLE
Runtime Warning given while  running with install_runtime: false

### ISSUE THREAD

**Issue by Lord-Grey** [jakoch/install-vulkan-sdk-action#416]
Hi @jakoch 

That is a great and simple to use action!

What is currently a bit confusing is, if I explicitly define "install_runtime: false" there is a warning issued  " Could not find Vulkan Runtime".
It would be great, if the warning is suppressed in the defined scenario.

Many thanks in advance!

Run jakoch/install-vulkan-sdk-action@v1.0.3
  with:
    **install_runtime: false**
    cache: true
    stripdown: true
  env:
    ghcr: hyperion-project
    VCINSTALLDIR: C:\Program Files\Microsoft Visual Studio\[2](https://github.com/hyperion-project/hyperion.ng/actions/runs/9520684623/job/26246483884#step:6:2)022\Enterprise\VC
Destination: C:\VulkanSDK\
Latest Version: 1.[3](https://github.com/hyperion-project/hyperion.ng/actions/runs/9520684623/job/26246483884#step:6:3).283.0
🎯 [Cache] Cache for 'Vulkan SDK' not found.
🔽 Downloading Vulkan SDK 1.3.283.0

...
🎯 [Cache] Saved Vulkan SDK in path: 'C:\VulkanSDK\1.3.283.0'. Cache Save ID: '[4](https://github.com/hyperion-project/hyperion.ng/actions/runs/9520684623/job/26246483884#step:6:4)09'.
✔️ [PATH] Added path to Vulkan SDK to environment variable PATH.
✔️ [ENV] Set env variable VULKAN_SDK -> "C:\VulkanSDK\1.3.2[8](https://github.com/hyperion-project/hyperion.ng/actions/runs/9520684623/job/26246483884#step:6:8)3.0".
✔️ [ENV] Set env variable VULKAN_VERSION -> "1.3.283.0".
**Warning: Could not find Vulkan Runtime in C:\VulkanSDK\1.3.283.0\runti**me
✅ Done.

**Comment by jakoch** [comment]
Hey Lord-Grey, good catch!

I forgot to add the check for `install_runtime` to the verification step: 
https://github.com/jakoch/install-vulkan-sdk-action/blob/v1.0.3/src/main.ts#L177
The install step has it: https://github.com/jakoch/install-vulkan-sdk-action/blob/v1.0.3/src/main.ts#L82

Bugfix incoming.

**Comment by jakoch** [comment]
Fixed and released v1.0.4.
